---
title: The Simpsons x tidytuesday
date: today
author:
  -
    name: Fran Barton
  -
    name: Gabriel Hobro
lang: en-GB
format: quafira-html
embed-resources: true
fig-dpi: 144
fig-height: 6
fig-width: 9
fig-responsive: true
lightbox: true
out-width: 92%
code-fold: true
execute:
  warning: false
  error: false
knitr:
  opts_knit:
    message: true
---

```{r setup}

# quarto use template francisbarton/quafira

library(dplyr)
library(ggplot2)
library(snakecase)
library(readr)
library(tvthemes)

```

```{r data-in}
#| cache: true

gh_tt_base <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/"
gh_tt_base_data <- paste0(gh_tt_base, "main/data/")
tt_date <- "2025/2025-02-04/"
rcsv <- \(x, ...) read_csv(paste0(gh_tt_base_data, tt_date, x), ...)


characters <- rcsv("simpsons_characters.csv", col_types = "dccc")
episodes <- rcsv("simpsons_episodes.csv", col_types = "dcddddDdcdcd--")
locations <- rcsv("simpsons_locations.csv", col_types = "dcc")
script_lines <- rcsv("simpsons_script_lines.csv", col_types = "dddcdlddccccd")

```

```{r data-view1}
#| code-fold: false

# glimpse(characters)
# glimpse(episodes)
# glimpse(locations)
glimpse(script_lines)

```

```{r plot1}
episodes2 <- episodes |>
  select(
    episode_id = "id",
    "season"
  )

main_chars <- script_lines |>
  filter(!is.na(raw_character_text)) |>
  count(raw_character_text, sort = TRUE) |>
  slice_head(n = 5) |>
  pull(raw_character_text)


script_lines |>
  rename(character = "raw_character_text") |>
  left_join(episodes2, "episode_id") |>
  filter(character %in% main_chars) |>
  summarise(
    words = sum(word_count, na.rm = TRUE),
    .by = c("character", "season")
  ) |>
  ggplot(aes(x = season, y = words)) +
  geom_col(aes(fill = character), position = "dodge") +
  labs(
    title = "Words spoken by season by the top 5 'Simpsons' characters",
    x = "Season",
    y = "Words spoken"
  ) +
  theme_simpsons() +
  scale_fill_simpsons(name = NULL)


```
